### ISSUE TITLE
optional chaining not working with function call

### ISSUE THREAD

**Issue by gabrielgrant** [babel/ember-cli-babel#332]
It was [previously reported that the optional chaining plugin wasn't working](#304 ). Since then [optional chaining has been enabled in Babel by default (as of v7.8.0)](https://github.com/babel/babel/issues/10809#issuecomment-578726419), but it appears it still isn't working with ember-cli 3.17.0 -- it fails at runtime for optional methods with "TypeError: _this$args3.onChange is not a function"

It seems
```
this.args?.onChange(selectedPlace);
```
 is getting compiled as
```
(_this$args3 = this.args) === null || _this$args3 === void 0 ? void 0 : _this$args3.onChange(selectedPlace);
```
It seems this version of ember-cli includes ember-cli-babel 7.18.0, which in turn should be using Babel ^7.8.4. I haven't found any reports of this being an issue in Babel, so wondering if this is ember-specific? but happy to report to Babel if it seems that's where this belongs.

**Comment by gabrielgrant** [comment]
Nvm, this is doing what it should be (I should have been doing `this.args.onChange?.(selectedPlace);`)
